const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const FixStyleOnlyEntriesPlugin = require('webpack-fix-style-only-entries');

module.exports = {
  mode: 'development',

  // You can add as much entries as you want here
  entry: {
    app: path.resolve(__dirname, 'src/js/app.js'),
    style: path.resolve(__dirname, 'src/css/style.css'),
  },

  // The output directories
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'js/[name].js',
    assetModuleFilename: 'assets/[name].[hash][ext][query]',
  },

  // The file extensions webpack should look for when you import a file without extension
  resolve: {
    extensions: ['.js'],
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'postcss-loader'],
      },
      {
        test: /\.(png|jpe?g|gif|svg|eot|ttf|woff|woff2)$/i,
        type: 'asset',
      },
    ],
  },

  plugins: [
    new FixStyleOnlyEntriesPlugin(), // remove the style.js file generated by webpack
    new MiniCssExtractPlugin({
      filename: 'css/[name].css',
    }),
  ],
};
